# Generated by Django 3.1.5 on 2021-01-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210111_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FilePathField(path='blog/static/articles/img/'),
        ),
    ]
